{
 "title": "Philips Hue",
 "description": "https://github.com/aexel90/hue_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "bridge",
    "label": "Bridge",
    "query": {
     "query": "label_values(hue_bridge_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hue_bridge_info{job=~\"$bridge\"}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hue_bridge_info{job=~\"$bridge\"}"
    }
   ]
  },
  {
   "title": "RemoteAccess",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hue_bridge_info{job=~\"$bridge\"}"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hue_bridge_info{job=~\"$bridge\"}"
    }
   ]
  },
  {
   "title": "Ziigbee Channel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hue_bridge_info{job=~\"$bridge\"}"
    }
   ]
  },
  {
   "title": "API Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hue_bridge_info{job=~\"$bridge\"}"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hue_bridge_info{job=~\"$bridge\"}"
    }
   ]
  },
  {
   "title": "Lights ON",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hue_light_state{job=~\"$bridge\"})"
    }
   ]
  },
  {
   "title": "Lights OFF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(hue_light_state{job=~\"$bridge\"})-sum(hue_light_state{job=~\"$bridge\"})"
    }
   ]
  },
  {
   "title": "Sensor Lightlevel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "10^((hue_sensor_lightlevel{job=~\"$bridge\"}-1)/10000)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sensor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hue_sensor_temperature{job=~\"$bridge\"}/100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sensor Overview",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hue_sensor_info{job=~\"$bridge\",type=~\"ZLL.*\"}"
    }
   ]
  },
  {
   "title": "Hue Light Overview",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "hue_light_info{job=~\"$bridge\"}"
    }
   ]
  }
 ]
}