{
 "title": "UniFi-Poller: Country Insights - Prometheus",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Region",
    "query": {
     "query": "label_values(unpoller_countrytraffic_receive_bytes_total,region)"
    }
   },
   {
    "name": "SubRegion",
    "label": "Sub-Region",
    "query": {
     "query": "label_values(unpoller_countrytraffic_receive_bytes_total{region=~\"$Region\"},sub_region)"
    }
   },
   {
    "name": "CountryCode",
    "label": "Country Code",
    "query": {
     "query": "label_values(unpoller_countrytraffic_receive_bytes_total{region=~\"$Region\"},code)"
    }
   },
   {
    "name": "Controller",
    "query": {
     "query": "label_values(unpoller_countrytraffic_receive_bytes_total,source)"
    }
   },
   {
    "name": "Site",
    "query": {
     "query": "label_values(unpoller_countrytraffic_receive_bytes_total,site_name)"
    }
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Country Traffic",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(code, name, region, sub_region, site_name, source) (unpoller_countrytraffic_receive_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"})"
    },
    {
     "expr": "sum by(code, name, region, sub_region, site_name, source) (unpoller_countrytraffic_transmit_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"})"
    }
   ]
  },
  {
   "title": "Bytes Rx By Country",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code, name) (unpoller_countrytraffic_receive_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Tx By Country",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code, name) (unpoller_countrytraffic_transmit_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Traffic By Country",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (code, name) (rate(unpoller_countrytraffic_receive_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"}[$__interval]))",
     "legendFormat": "{{name}} Rx"
    },
    {
     "expr": "sum by (code, name) (rate(unpoller_countrytraffic_transmit_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"}[$__interval]))",
     "legendFormat": "{{name}} Tx"
    }
   ]
  },
  {
   "title": "Bytes Rx By Region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, sub_region) (unpoller_countrytraffic_receive_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"})",
     "legendFormat": "{{region}} / {{sub_region}}"
    }
   ]
  },
  {
   "title": "Bytes Tx By Region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, sub_region) (unpoller_countrytraffic_transmit_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"})",
     "legendFormat": "{{region}} / {{sub_region}}"
    }
   ]
  },
  {
   "title": "Traffic By Region / Sub-Region",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (region, sub_region) (rate(unpoller_countrytraffic_receive_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"}[$__interval]))",
     "legendFormat": "{{region}} / {{sub_region}} Rx"
    },
    {
     "expr": "sum by (region, sub_region) (rate(unpoller_countrytraffic_transmit_bytes_total{site_name=~\"$Site\", source=~\"$Controller\", code=~\"$CountryCode\", region=~\"$Region\", sub_region=~\"$SubRegion\"}[$__interval]))",
     "legendFormat": "{{region}} / {{sub_region}} Tx"
    }
   ]
  }
 ]
}