keys:
  - &ij age1vc68fqwnlflkcz7vnpv43azqr50dtpcztxrlaudsux7y6qyj8ysqcyugwg
  - &mkj age1dwkcncendgjwsn2r64c5muxah8nkcyfkjfk00nxucp43vnrzn3ds9rd0s3
  - &pakhet age1wwxaaahz6gp8f8t44m2kyqr2h4zwgn85fqjuls0rqypm958r342qtxhvq0
  - &macbook age1vc68fqwnlflkcz7vnpv43azqr50dtpcztxrlaudsux7y6qyj8ysqcyugwg
  - &goose age1w3txsuslrkv7m8jak3lqkwyu6624p55ewrjyprwzdzwxpfgjkvxsh9y0dz
  - &khosu age1t7cj3yeyge87wk4fcljur5wv0fap68fyqjrf8fzk7vppv2v5qfmqpuhzfy
  - &anubis age1r0phf8m20r0jcypw4f7c2r7nh54rr32audrld5ssky48ck8gpuzs47d5ds
  - &bastet age1harfm00p7lwgx2xtzy7dcm5ez4wgjlk7nm9zzghezg7kc8vz3djqnde324

creation_rules:
  - path_regex: secrets/goose\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *ij
          - *mkj
          - *goose

  - path_regex: secrets/khosu\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *ij
          - *mkj
          - *khosu

  - path_regex: secrets/anubis\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *ij
          - *mkj
          - *anubis

  - path_regex: secrets/pakhet\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *ij
          - *mkj
          - *pakhet

  - path_regex: secrets/bastet\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *ij
          - *mkj
          - *bastet

  - path_regex: secrets/macbook\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *ij
          - *macbook
